### ISSUE TITLE
Image URLs do not contain Cloudfront-Domain

### ISSUE THREAD

**Issue by sattes-faction** [gatherdigitaluk/pimcore-plugin-s3#1]
Hi,

I successfully installed the plugin and it's working quite well so far. 

But I'm having a problem that the Image-URLs on a page don't use the cloudfront-domain path (e.g. `http://aabbccddeeff.cloudfront.net/testfolder/myimage.jpg`) but just the relative one (`/testfolder/myimage.jpg`). Am I missing something? Do I have to configure it somewhere?

Thanks!

Great work btw with the plugin.

**Comment by cleggypdc** [comment]
hey @sattes-faction (wow i totally missed this notification)

The plugin doesn't support cloudfront URL's only the default S3 URI. Tbh I haven't used Cloudfront, but insight into how this could be added (or PR's are welcomed)

Cheers!

**Comment by sattes-faction** [comment]
Hi cleggy, ok I see - in the meantime I switched back to the pimcore way of using s3 (for some other reasons, not only because of cloudfront) - though the plugin approach is imo a little bit better. Thanks for your reply though :+1:
